// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi319Sr5p7c4d9WJJkKoMF6_oaJ8Ea6Gs',
    appId: '1:65043718768:web:57d47363c9af3f511ccab5',
    messagingSenderId: '65043718768',
    projectId: 'e-tick',
    authDomain: 'e-tick.firebaseapp.com',
    storageBucket: 'e-tick.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrQND-X-X9feQiHezX-eWVSSeqfDIGns',
    appId: '1:65043718768:android:eb9a20aa555f3c791ccab5',
    messagingSenderId: '65043718768',
    projectId: 'e-tick',
    storageBucket: 'e-tick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2e8NN6sIbrlvLroa1b5yHuEwbdm-bZ1I',
    appId: '1:65043718768:ios:143b94eaf9306f7d1ccab5',
    messagingSenderId: '65043718768',
    projectId: 'e-tick',
    storageBucket: 'e-tick.appspot.com',
    iosClientId: '65043718768-5ip28p2tkvhi3rff5al4klh74lo9mfsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2e8NN6sIbrlvLroa1b5yHuEwbdm-bZ1I',
    appId: '1:65043718768:ios:143b94eaf9306f7d1ccab5',
    messagingSenderId: '65043718768',
    projectId: 'e-tick',
    storageBucket: 'e-tick.appspot.com',
    iosClientId: '65043718768-5ip28p2tkvhi3rff5al4klh74lo9mfsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eTick',
  );
}
